### GENERAL SETTINGS ###

# Site settings
title: PrivatE, Reliable and SecUrE Computing Lab (PERSUE)
title_abbreviation: PERSUE
description: "Website for the Privacy and Security Lab, School of Computing and Augmented Intelligence at Arizona State University."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://privacy-and-security-lab.github.io"

# Build settings
markdown: kramdown
# permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#9D2235" #"#a30046"
  primary_rgb: "157, 34, 53" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#474747" #"#33004D"
  link: "#428bca"
  link_hover: "#9D2235"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

collections:
  team_members:
    output: true
    permalink: /team/:title/
  project_details:
    output: true
    permalink: /projects/:title/

# Projects
projects:
  - name: "Privacy on social platforms"
    img: "privacy-on-social-platforms.png"
    link: "privacy-on-social-platforms"
  - name: "Privacy, Security, and Safety issues in Education Technology"
    img: "edtech.png"
    link: "privacy-security-and-safety-issues-in-education-technology"
  - name: "Interdependent and multi-party privacy"
    img: "interdependent-privacy.png"
    link: "interdependent-and-multi-party-privacy"

# Faculty
faculty:
  - name: "Dr. Rakibul Hasan"
    position: Faculty
    img: dr_rakibul_hasan.png
    details_link: dr-rakibul-hasan

# Current graduate students
current_grad_students:
  - name: "Protik Bose Pranto"
    position: Ph.D. student
    img: protik_bose_pranto.jpg
    details_link: protik-bose-pranto
  - name: "Waqar Hassan Khan"
    position: Ph.D. student
    img: waqar_hassan_khan.jpeg
    details_link: waqar-hassan-khan


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We aim to enhance the privacy, security, and reliability of computing technologies. Our research activities identify and understand privacy, security, and reliability issues with information technologies and explore mitigation strategies toward a safer technology ecosystem. We take a human-centered perspective to understand the problem space while combining techniques from AI and Machine Learning, Internet Measurement, Cognitive Psychology, and Statistical Causal Inference methodologies to solve the identified problems."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
