---
label: Service
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: author
  label: author
- type: list
  name: categories
  label: categories
- type: file
  name: img
  label: img
- type: file
  name: thumb
  label: thumb
- type: image_gallery
  name: carousel
  label: carousel
- type: text
  name: tagged
  label: tagged
